### ISSUE TITLE
Comparison to upstream

### ISSUE THREAD

**Issue by Konfekt** [builtbyvichingo455/Mini10#1]
Hello,

would you mind explaining from which upstream verson of Tiny 10 these ISOs derive and how they differ, in particular regarding privacy?

Thank you very much for this useful ISO, its working splendidly in VirtualBox.

**Comment by Vichingo455** [comment]
Well it's actually more customizable. I added several plugins allowing the user to customize the ISO.
Also I deleted some useless non-working junk like the activator (it wasn't going to run it at first login).
Also putted a background in the desktop and logonui.
Also I pre-patched uxtheme allowing the user to install custom themes
